name: Sync to Hugging Face Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  HF_REPO_ID: iamtatsuki05/ocr_and_translate_en2jp
  HF_REPO_TYPE: space
  HF_SPACE_SDK: docker

concurrency:
  group: sync-to-hub-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Hugging Face CLI
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade "huggingface_hub[cli]"

      - name: Create/Configure Space (idempotent)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python - <<'PY'
          import os
          from huggingface_hub import HfApi
          token = os.environ["HF_TOKEN"]
          api = HfApi(token=token)
          repo_id = os.environ["HF_REPO_ID"]
          repo_type = os.environ.get("HF_REPO_TYPE", "space")
          space_sdk = os.environ.get("HF_SPACE_SDK", "docker")
          # 既存ならOK、未作成なら作成
          api.create_repo(repo_id=repo_id, repo_type=repo_type, exist_ok=True)
          # SpaceのSDKを設定（古いhubでは未実装の場合があるため例外は握りつぶす）
          try:
              api.update_space_settings(repo_id=repo_id, sdk=space_sdk)
          except Exception as e:
              print("[warn] update_space_settings skipped:", e)
          PY

      - name: Upload repository content (diff-aware)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # .hfignore がなければ最低限を生成
          if [ ! -f .hfignore ]; then
            cat > .hfignore << 'IGN'
            .git/
            .github/
            **/__pycache__/
            *.py[cod]
            .venv/
            venv/
            dist/
            build/
            .tox/
            .ipynb_checkpoints/
            IGN
          fi
          huggingface-cli upload \
            . \
            . \
            --repo-id "$HF_REPO_ID" \
            --repo-type "$HF_REPO_TYPE" \
            --token "$HF_TOKEN" \
            --exclude-from .hfignore \
            --delete

      - name: Show Hub URL
        run: |
          case "$HF_REPO_TYPE" in
            space) echo "Space URL: https://huggingface.co/spaces/$HF_REPO_ID" ;;
            model) echo "Model URL: https://huggingface.co/$HF_REPO_ID" ;;
            dataset) echo "Dataset URL: https://huggingface.co/datasets/$HF_REPO_ID" ;;
          esac

